"""Adding Password Column & Constraints for email column - Second Migartion

Revision ID: 4a77e704496a
Revises: 9339066bc326
Create Date: 2026-08-18 16:12:29.252841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a77e704496a'
down_revision: Union[str, Sequence[str], None] = '9339066bc326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=150), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
